In [1]:
import pandas as pd
import numpy as np
import sympy as sym

In [7]:
#create a random normolized 5X5 matrix with values between 0 and 100
A = np.random.randint(0,100,50).reshape(10,5)
A = pd.DataFrame(A, columns=['A','B','C','D','E'])
A

    A   B   C   D   E
0  50  61  11   9  94
1  38  69  15   4  43
2  58  88  44  67  55
3  95  15   8  56  53
4  18  99  79  23  93
5  20  67  43  48   1
6  17  90  41  67  28
7  50  43   0  37  40
8  90  98  35  90  39
9  39  70  85  38  36